### PR TITLE
Skip and warn when not able to retreive a service

### LINKED ISSUE #30: Add option to skip generating services for repositories with branches that couldn't be found
Maybe we should look into adding a flag to SwaggerSwift that allows it to skip services if it can't find the branch. It's a small annoyance to have to modify the specification for a service that you don't know anything because the branch no longer exists and when we're justing updating a single service.

Alternatively we could add a flag to specify specific services to update but then we can't just reuse a command in our history.

For context this is the kind of error SwaggerSwift is currently throwing when failing to fetch a repository:

> SwaggerSwift/SwaggerFileParser.swift:38: Fatal error: Failed to download Swagger from: https://raw.githubusercontent.com/lunarway/oedd-service/feature/adds_swagger/api/swagger.yaml

### PR DESCRIPTION
**Pull request by mxsc**
Don't fail if not being able to download a swagger file, instead just skip, fixes #30

### CODE REVIEW

File: Sources/SwaggerSwift/SwaggerFileParser/SwaggerFileParser.swift [hunk 1]
```diff
@@ -35,7 +35,10 @@ struct SwaggerFileParser {
             dispatchGroup.enter()
             URLSession.shared.dataTask(with: request) { data, response, error in
                 if let httpResponse = response as? HTTPURLResponse, httpResponse.statusCode != 200 {
-                    fatalError("Failed to download Swagger from: \(request.url?.absoluteString ?? "")")
+                    print("Failed to download Swagger from: \(request.url?.absoluteString ?? "")")
```
Comment (MadsBogeskov) [inline Sources/SwaggerSwift/SwaggerFileParser/SwaggerFileParser.swift:38]: Could we float this up to fastlane in any way so we don't suddenly just loose services?

Comment (mxsc) [reply Sources/SwaggerSwift/SwaggerFileParser/SwaggerFileParser.swift:38]: as far as I know fastlane should be able to print this in its log.

**Comment by mxsc** [comment]
I just noticed that this might create an issue when a service is renamed. As part of this PR the directory deletion is done in swaggerswift to avoid deleting APIs that we fail to fetch. In this case I think we have to manually delete the folder in the output directory.

**Review by MadsBogeskov — APPROVED** [review]
